### ISSUE TITLE
the JSON values should not contain HTML

### ISSUE THREAD

**Issue by egonw** [youphendriks/TGX-overview#2]
I would suggest to split the layout from the content fully. That would also mean no HTML tags in the JSON field content, like in https://raw.githubusercontent.com/youphendriks/TGX-overview/refs/heads/main/db/BridgeDB/BridgeDB.json

**Comment by youphendriks** [comment]
Fixed with [Commit switching HTML formatting AFTER saving jsons](https://github.com/youphendriks/TGX-overview/commit/5bb03738bbcfe0a87cf0350cdecd499658f875a6)
